### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-omnifaces#1]
@all-contributors add @melloware for code and maintenance

**Comment by melloware** [comment]
https://github.com/all-contributors add @melloware for code and maintenance

**Comment by gastaldi** [comment]
You need to add as a comment in the issue, the bot doesn't work if it's the first issue comment

**Comment by gastaldi** [comment]
@all-contributors add @melloware for code and maintenance

**Comment by melloware** [comment]
that did it!
