### ISSUE TITLE
Manifest not detected in Quarkus-Omnifaces extension

### ISSUE THREAD

**Issue by felipelx07** [quarkiverse/quarkus-omnifaces#72]
I've configured the PWAResourceHandler on my Quarkus + Myfaces Application but the manifest.json can't be detected.
I debug the code and see the manifest generating the file. But the manifest is not recognized.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/5168904/233119833-3addfd74-ed32-4d68-adae-929f2cfb58ee.png">

Quarkus: 2.16.3.Final
Quarkus-Omnifaces: 3.14.3

Someone can help ?

**Comment by melloware** [comment]
I see the issue.   Might need to fix both Quarkus OmniFaces AND OmniFaces to make it work.

**Comment by melloware** [comment]
@felipelx07 can you try just adding `@Named` to your Manifest like this..

```java
@Named
@ApplicationScoped
public class ManifestJson extends WebAppManifest {
```

Does that now work for you?

**Comment by felipelx07** [comment]
Its work mate! Thank you

**Comment by melloware** [comment]
I am going to work a better fix but that should keep you working for now.

**Comment by melloware** [comment]
@all-contributors add @felipelx07 for bug
